# Generated by Django 3.1.7 on 2021-04-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_Name', models.CharField(max_length=150)),
                ('P_Email', models.EmailField(max_length=100)),
                ('P_Complaint', models.CharField(max_length=2000)),
            ],
        ),
    ]
